services:
  backend:
    build:
      context: /backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
    restart: always
    networks:
      - wattwise_network
  database:
    image: timescale/timescaledb-ha:pg14-latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - /database/timescaledb/data:/var/lib/postgresql/data
      - /database/timescaledb/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - /database/timescaledb/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    restart: always
    networks:
      - wattwise_network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
networks:
  wattwise_network:
    driver: bridge