version: "2.23"

services:
  frontend:
    container_name: frontend
    build:
      context: /frontend
      dockerfile: Dockerfile
    env_file:
      - docker.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    networks:
      - wattwise_frontend_backend
  backend:
    container_name: backend
    env_file:
      - docker.env
    build:
      context: /backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
    restart: always
    networks:
      - wattwise_frontend_backend
      - wattwise_internal
  database:
    container_name: database
    image: timescale/timescaledb:latest-pg14
    env_file:
      - docker.env
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - wattwise_internal

volumes:
  database_data:
    driver: local
  redis_data:
    driver: local
networks:
  wattwise_internal:
    driver: bridge
  wattwise_frontend_backend:
    driver: bridge

